### ISSUE TITLE
Query timeout limit reached while updating German Nouns

### ISSUE THREAD

**Issue by shashank-iitbhu** [scribe-org/Scribe-Data#124]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description
```shell
(scribedev) shashankmittal@ShashanksLaptop Scribe-Data % python3 src/scribe_data/extract_transform/wikidata/update_data.py '["German"]' '["nouns", "verbs"]' 
Data updated:   0%|                                                                                                                   | 0/2 [00:00<?, ?dirs/s]Querying and formatting German nouns
Data updated:   0%|                                                                                                                   | 0/2 [01:00<?, ?dirs/s]
Traceback (most recent call last):
  File "/Users/shashankmittal/Documents/Developer/scribe/Scribe-Data/src/scribe_data/extract_transform/wikidata/update_data.py", line 141, in <module>
    results = sparql.query().convert()
  File "/opt/anaconda3/envs/scribedev/lib/python3.10/site-packages/SPARQLWrapper/Wrapper.py", line 1196, in convert
    return self._convertJSON()
  File "/opt/anaconda3/envs/scribedev/lib/python3.10/site-packages/SPARQLWrapper/Wrapper.py", line 1059, in _convertJSON
    json_str = json.loads(self.response.read().decode("utf-8"))
  File "/opt/anaconda3/envs/scribedev/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/anaconda3/envs/scribedev/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/anaconda3/envs/scribedev/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 320797 column 115 (char 6713171)
``` 

Query builder [Link](https://query.wikidata.org/#%23%20All%20German%20%28Q188%29%20nouns%2C%20their%20plural%20and%20their%20gender.%0A%23%20Enter%20this%20query%20at%20https%3A%2F%2Fquery.wikidata.org%2F.%0A%0ASELECT%20DISTINCT%0A%20%20%28REPLACE%28STR%28%3Flexeme%29%2C%20%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2F%22%2C%20%22%22%29%20as%20%3FlexemeID%29%0A%20%20%3Fsingular%0A%20%20%3Fplural%0A%20%20%3Fgender%0A%0AWHERE%20%7B%0A%20%20%23%20Nouns%20and%20pronouns.%0A%20%20VALUES%20%3FnounTypes%20%7B%20wd%3AQ1084%20wd%3AQ147276%20%7D%0A%20%20%3Flexeme%20a%20ontolex%3ALexicalEntry%20%3B%0A%20%20%20%20dct%3Alanguage%20wd%3AQ188%20%3B%0A%20%20%20%20wikibase%3AlexicalCategory%20%3Fnoun%20.%0A%20%20FILTER%28%3Fnoun%20%3D%20%3FnounTypes%29%0A%0A%20%20%23%20Optional%20selection%20of%20nominative%20singular%20forms.%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%3Flexeme%20ontolex%3AlexicalForm%20%3FsingularForm%20.%0A%20%20%20%20%3FsingularForm%20ontolex%3Arepresentation%20%3Fsingular%20%3B%0A%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ110786%20%3B%0A%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ131105%20%3B%0A%20%20%7D%20.%0A%0A%20%20%23%20Optional%20selection%20of%20nominative%20plural%20forms.%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%3Flexeme%20ontolex%3AlexicalForm%20%3FpluralForm%20.%0A%20%20%20%20%3FpluralForm%20ontolex%3Arepresentation%20%3Fplural%20%3B%0A%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ146786%20%3B%0A%20%20%20%20%20%20wikibase%3AgrammaticalFeature%20wd%3AQ131105%20%3B%0A%20%20%7D%20.%0A%0A%20%20%23%20Optional%20selection%20of%20genders.%0A%20%20OPTIONAL%20%7B%0A%20%20%20%20%3Flexeme%20wdt%3AP5185%20%3FnounGender%20.%0A%20%20%20%20FILTER%20NOT%20EXISTS%20%7B%20%3Flexeme%20wdt%3AP31%20wd%3AQ202444%20.%20%7D%0A%20%20%7D%20.%0A%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%0A%20%20%20%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%22.%0A%20%20%20%20%3FnounGender%20rdfs%3Alabel%20%3Fgender%20.%0A%20%20%7D%0A%7D%0A)

The query time limit is reached that's why `results = sparql.query().convert()` in `update_data.py` is throwing `json.decoder.JSONDecodeError` due to Invalid control character at: line 320797 column 115 (char 6713171) in `sparql.query().response` as it contains the timeout error logs.

### Suggested Changes
- Considered splitting SPARQL query into smaller queries, such as one query for nouns and another for pronouns, or querying for singular and plural forms separately.
- Still got `Query timeout limit reached` error as total number of nouns and pronouns for German are 165869. Verified [here](https://query.wikidata.org/#%23%20Count%20the%20total%20number%20of%20German%20%28Q188%29%20nouns%20and%20pronouns.%0A%23%20Enter%20this%20query%20at%20https%3A%2F%2Fquery.wikidata.org%2F.%0A%0ASELECT%20%28COUNT%28DISTINCT%20%3Flexeme%29%20AS%20%3FtotalNounsAndPronouns%29%0AWHERE%20%7B%0A%20%20%23%20Nouns%20and%20pronouns.%0A%20%20VALUES%20%3FnounTypes%20%7B%20wd%3AQ1084%20wd%3AQ147276%20%7D%0A%20%20%3Flexeme%20a%20ontolex%3ALexicalEntry%20%3B%0A%20%20%20%20dct%3Alanguage%20wd%3AQ188%3B%0A%20%20%20%20wikibase%3AlexicalCategory%20%3FnounTypes%20.%0A%7D%0A).
- Use `LIMIT` and `OFFSET` to split into multiple queries.

**Comment by shashank-iitbhu** [comment]
This can be reproduced by running: `python3 src/scribe_data/extract_transform/wikidata/update_data.py '["German"]' '["nouns", "verbs"]'`
@andrewtavis Are you able to reproduce this issue?
If so, I can open a PR with the proposed changes.

**Comment by andrewtavis** [comment]
I can confirm on my end, @shashank-iitbhu:

```
json.decoder.JSONDecodeError: Invalid control character at: line 320797 column 115 (char 6713171)
```

Two questions to decide on this:
- Could you do a query of just nouns and just pronouns and let us know what the percentage of the total each is?
- For `LIMIT` and `OFFSET` I'm a bit worried that it might not work as we'd need to compute the full result in order to then offset for the ones we want?
  - This would maybe we a solution if the result JSON was too large, but then this issue is query time
  - I can check with folks at work on this 😇

All in all great that you figured this out and suggested solutions! As you can see by the verbs queries, this is not the first time that this has happened 😅

**Comment by andrewtavis** [comment]
Confirmed from the Wikidata team that splitting based on nouns and proper nouns would be the initial path forward, but offset could work if it continues to be problematic :)

**Comment by andrewtavis** [comment]
Note that I just tried to query only all the singulars of only the nouns, not the proper nouns, and it's still failing. At this point it might make sense to use `LIMIT` and `OFFSET`.

**Comment by andrewtavis** [comment]
CC @daveads, do you want to write in here so I can assign this issue to you?

**Comment by andrewtavis** [comment]
Lots of commits above, and post a discussion with a Wikidata admin today I was able to get it working with changes to the query itself. This issue has been great for Scribe as it really unveiled a lot of parts of the queries that weren't necessary and were slowing things down. Note on this as well: maybe something to consider if a query stops is to remove the labeling service if it's been used, as there is a lot of overhead to get it to run over the results of a large query. 

With the above being said, there have been lots of improvements, and I'm super grateful to @shashank-iitbhu for opening this and to @daveads for all the conversations that led to the possible solutions that led us to here! 😊 Thanks so much!
